apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: '2021-02-17T08:19:14Z'
  labels:
    name: filebeat-docker-build
  name: filebeat-docker-build
  namespace: kuba-test
  resourceVersion: '780799440'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/kuba-test/buildconfigs/filebeat-docker-build
  uid: d26331f0-70f8-11eb-8626-0050568f0885
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector:
    kubernetes.io/hostname: vihlaose017.vih.infineon.com
  output:
    to:
      kind: ImageStreamTag
      name: 'filebeat-docker:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: 'https://github.com/chalamonski/filebeat.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange